services:
  app:
    # image: sjwright90/dash-spatial-app:latest
    build: .
    container_name: dash_gunicorn
    restart: always
    networks:
      - webnet
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      # - ./nginx/ssl:/etc/nginx/ssl
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - webnet
networks:
  webnet: